apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql2
  template:
    metadata:
      labels:
        app: mysql2
    spec:
      containers:
      - name: mysql-container
        image: bitnami/mysql:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: "db2"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /bitnami/mysql/data

      volumes:  # This should be at the same indentation level as containers
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql2
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
