apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql2
  template:
    metadata:
      labels:
        app: mysql2
    spec:
      containers:
      - name: mysql-container
        image: bitnami/mysql:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: php-app-config
              key: schema.sql # Use the schema.sql from the ConfigMap
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /bitnami/mysql/data

      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: php-app-config
        configMap:
          name: php-app-config
